//! The 256-case Marching Cubes table, **derived at compile time**.
//!
//! # Why this is generated rather than transcribed
//!
//! The implementation brief is explicit that the table must not be typed from
//! memory, because a wrong entry produces a mesh that looks fine and is silently
//! non-manifold. It offers two defences: take the table from a cited source, and
//! write a validator that checks all 256 cases without a reference table.
//!
//! The papers are in the local corpus — Lewiner et al., *Efficient
//! Implementation of Marching Cubes' Cases with Topological Guarantees*, Journal
//! of Graphics Tools 8:2 (2003), `10.1080/10867651.2003.10487582`, and Lengyel's
//! 2010 Transvoxel dissertation — but **their case tables did not survive
//! PDF-to-text conversion**: Lengyel's Tables 3.1 and 3.2 are figures of cube
//! diagrams, and Lewiner's Table 1 converts to scrambled cells. Reading
//! triangulations off diagrams is the guessing the rules forbid.
//!
//! So the table is *constructed* instead, which removes the transcription
//! entirely, and then checked — see [`super::validate_table`]. What is taken
//! from Lengyel (dissertation §3.1.1, p.20) is the structure and the
//! conventions, not the numbers:
//!
//! - the 8-bit case index is the concatenated inside/outside corner bits;
//! - *"a positive value means that a sample point is outside the terrain in
//!   empty space, and a negative value means that it is inside it in solid
//!   space"* — which is this crate's sign convention;
//! - *"A choice must be made globally as to whether a sample value of exactly
//!   zero is considered to be in empty space or in solid space, and a consistent
//!   classification either way is acceptable."* See [`is_inside`].
//!
//! # The construction
//!
//! For one corner-sign configuration:
//!
//! 1. A cube edge is **cut** when its two corners are classified differently.
//!    Surface vertices live on cut edges, one each.
//! 2. On each face, walk the four corners counter-clockwise *as seen from
//!    outside the cube*. Each maximal run of inside corners is entered at one
//!    cut edge and left at another, giving a directed segment across that face.
//! 3. **Every cut edge gets exactly one outgoing and one incoming segment.** A
//!    cut edge lies on exactly two faces, and two faces of a cube with outward
//!    normals induce *opposite* directions on their shared edge — so it is an
//!    entry on one and an exit on the other. The segments therefore link the cut
//!    edges into directed cycles with no choices left over.
//! 4. Fan-triangulate each cycle.
//!
//! Nothing in that is a lookup, so there is nothing to mistype. Step 3 is also
//! what makes the result crack-free: a face's segments are a function of that
//! face's own four corner signs, so two cells sharing a face necessarily agree
//! on it. `face_segments_depend_only_on_that_face` checks exactly that.
//!
//! # The one real choice
//!
//! Step 2 resolves an ambiguous face — one with two diagonally opposite inside
//! corners — by **separating the inside corners**, since each run of inside
//! corners is cut off by its own segment. Both pairings are crack-free as long
//! as the rule is applied consistently, which is why this is a decision rather
//! than a fact. Marching Cubes proper has no way to do better; MC33's asymptotic
//! decider replaces this rule with one that reads the bilinear saddle, and that
//! is A-002's ticket.
//!
//! Interior ambiguity is likewise left alone: where a cell could host either two
//! separate sheets or a tunnel, this construction produces separate sheets.
//! Custodio et al. (2013) put the practical cost in perspective — the vast
//! majority of real-world cells match the unambiguous configurations, and a game
//! needs topological *consistency*, which this has, rather than topological
//! *correctness*, which needs the interior test.

/// Corner `i` sits at local coordinate `(i & 1, (i >> 1) & 1, (i >> 2) & 1)`.
///
/// So bit 0 is x, bit 1 is y, bit 2 is z — matching the crate's x-varies-fastest
/// index order.
pub const CORNER_COUNT: usize = 8;

/// A cube has twelve edges.
pub const EDGE_COUNT: usize = 12;

/// Upper bound on triangles per cell.
///
/// The construction cannot exceed this; `no_case_exceeds_the_triangle_bound`
/// records the maximum actually reached.
pub const MAX_TRIANGLES: usize = 12;

/// Marker for "no edge".
pub const NO_EDGE: u8 = u8::MAX;

/// The two corners of each edge, lower corner first.
///
/// Generated by walking axes x, y, z and, within each, the four corners whose
/// bit for that axis is zero. Deterministic, and the numbering is therefore this
/// crate's rather than any paper's — which is fine precisely because nothing is
/// being cross-referenced against a paper's numbering.
pub const EDGE_CORNERS: [[u8; 2]; EDGE_COUNT] = build_edge_corners();

const fn build_edge_corners() -> [[u8; 2]; EDGE_COUNT] {
    let mut out = [[0u8; 2]; EDGE_COUNT];
    let mut n = 0;
    let mut axis = 0u8;
    while axis < 3 {
        let mut c = 0u8;
        while c < 8 {
            if c & (1 << axis) == 0 {
                out[n] = [c, c | (1 << axis)];
                n += 1;
            }
            c += 1;
        }
        axis += 1;
    }
    out
}

/// The axis each edge runs along.
pub const EDGE_AXIS: [u8; EDGE_COUNT] = build_edge_axis();

const fn build_edge_axis() -> [u8; EDGE_COUNT] {
    let mut out = [0u8; EDGE_COUNT];
    let mut e = 0;
    while e < EDGE_COUNT {
        let d = EDGE_CORNERS[e][0] ^ EDGE_CORNERS[e][1];
        out[e] = match d {
            1 => 0,
            2 => 1,
            _ => 2,
        };
        e += 1;
    }
    out
}

/// Index of the edge joining two corners.
///
/// # Panics
///
/// At compile time, if the two corners are not adjacent on the cube.
pub const fn edge_index(a: u8, b: u8) -> u8 {
    let (lo, hi) = if a < b { (a, b) } else { (b, a) };
    let mut e = 0;
    while e < EDGE_COUNT {
        if EDGE_CORNERS[e][0] == lo && EDGE_CORNERS[e][1] == hi {
            return e as u8;
        }
        e += 1;
    }
    panic!("corners are not joined by a cube edge")
}

/// The four corners of a face, counter-clockwise **as seen from outside**.
///
/// `axis` is the face's normal axis and `side` selects the near (`0`) or far
/// (`1`) face along it. With `u = (axis+1) % 3` and `v = (axis+2) % 3` the
/// triple `(u, v, axis)` is right-handed, so on the far face the viewer sees
/// `u × v` pointing at them and counter-clockwise runs `00 → 10 → 11 → 01`; on
/// the near face they see it pointing away, and the order reverses.
///
/// Getting this backwards on one face out of six would not fail to compile and
/// would not fail an edge-manifold check — it would produce an inside-out patch.
/// That is what `validate::MeshReport::inconsistently_oriented_edges` and the
/// signed-volume test exist to catch.
pub const fn face_corners(axis: usize, side: u8) -> [u8; 4] {
    let u = (axis + 1) % 3;
    let v = (axis + 2) % 3;
    let base = side << axis;
    let c00 = base;
    let c10 = base | (1 << u);
    let c11 = base | (1 << u) | (1 << v);
    let c01 = base | (1 << v);
    if side == 1 {
        [c00, c10, c11, c01]
    } else {
        [c00, c01, c11, c10]
    }
}

/// Is this corner inside the solid, for the given case index?
#[inline]
pub const fn corner_inside(case: u8, corner: u8) -> bool {
    case & (1 << corner) != 0
}

/// The global rule for classifying a sample.
///
/// **A sample of exactly zero is outside.** Lengyel notes the choice has to be
/// made once and applied everywhere, and that either answer is acceptable so
/// long as it is consistent.
///
/// Choosing strict `< 0` buys something concrete: on a cut edge one endpoint is
/// then strictly negative and the other is `>= 0`, so `a - b` is strictly
/// negative and the interpolation `t = a / (a - b)` can never divide by zero.
/// The brief's suggested `|a - b| < eps → t = 0.5` guard is therefore not needed
/// at all — and is actively unwanted, since an epsilon there would snap
/// genuinely resolvable crossings to the edge midpoint and blunt exactly the
/// sub-voxel features A-014 exists to recover.
#[inline]
pub fn is_inside<R: crate::Real>(value: R) -> bool {
    value < R::ZERO
}

/// The triangulation for one corner-sign configuration.
#[derive(Clone, Copy, Debug)]
pub struct McCase {
    /// Number of triangles.
    pub count: u8,
    /// Each triangle as three edge indices. Only the first `count` are valid.
    pub triangles: [[u8; 3]; MAX_TRIANGLES],
}

/// All 256 configurations, built during compilation.
pub static CASES: [McCase; 256] = build_cases();

const fn build_cases() -> [McCase; 256] {
    let mut out = [McCase {
        count: 0,
        triangles: [[0u8; 3]; MAX_TRIANGLES],
    }; 256];
    let mut case = 0usize;
    while case < 256 {
        out[case] = build_case(case as u8);
        case += 1;
    }
    out
}

/// Segment links for one configuration: `next[e]` is the cut edge the segment
/// leaving cut edge `e` arrives at, or [`NO_EDGE`].
///
/// Exposed so the validator can rebuild them independently of the triangles.
pub const fn segment_links(case: u8) -> [u8; EDGE_COUNT] {
    let mut next = [NO_EDGE; EDGE_COUNT];

    let mut axis = 0usize;
    while axis < 3 {
        let mut side = 0u8;
        while side < 2 {
            let c = face_corners(axis, side);

            // Start the walk on an outside corner so the first transition seen
            // is an entry. If every corner is inside, the face is not cut.
            let mut start = 4usize;
            let mut k = 0usize;
            while k < 4 {
                if !corner_inside(case, c[k]) {
                    start = k;
                    break;
                }
                k += 1;
            }

            if start < 4 {
                let mut entry = NO_EDGE;
                let mut j = 0usize;
                while j < 4 {
                    let p = c[(start + j) % 4];
                    let q = c[(start + j + 1) % 4];
                    let p_in = corner_inside(case, p);
                    let q_in = corner_inside(case, q);
                    if !p_in && q_in {
                        entry = edge_index(p, q);
                    } else if p_in && !q_in {
                        next[entry as usize] = edge_index(p, q);
                    }
                    j += 1;
                }
            }

            side += 1;
        }
        axis += 1;
    }

    next
}

const fn build_case(case: u8) -> McCase {
    let next = segment_links(case);

    let mut triangles = [[0u8; 3]; MAX_TRIANGLES];
    let mut count = 0usize;
    let mut visited = [false; EDGE_COUNT];

    let mut e = 0usize;
    while e < EDGE_COUNT {
        if next[e] != NO_EDGE && !visited[e] {
            // Walk the cycle this cut edge belongs to.
            let mut cycle = [0u8; EDGE_COUNT];
            let mut len = 0usize;
            let mut cur = e as u8;
            while !visited[cur as usize] {
                visited[cur as usize] = true;
                cycle[len] = cur;
                len += 1;
                cur = next[cur as usize];
            }

            // Fan from the first vertex. Every cycle has at least three edges:
            // two distinct cube edges share at most one face, so no two-cycle
            // can form.
            let mut i = 1usize;
            while i + 1 < len {
                triangles[count] = [cycle[0], cycle[i], cycle[i + 1]];
                count += 1;
                i += 1;
            }
        }
        e += 1;
    }

    McCase {
        count: count as u8,
        triangles,
    }
}
